name: Creating an example 5G NF downloadable artifact

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build
      run: make build
    - name: Upload NF
      uses: actions/upload-artifact@v4
      with:
          name: NF
          path: NF
    #First mount the required drive to the remote server after setting up Github actions. Then push it
    - name: Prepare network drive folder
      run: |
          mkdir -p /mnt/saimanoj-artifacts
    - name: Copy artifact to network drive
      run: |
          cp NF /mnt/saimanoj-artifacts
